echo Extract rootfs.es...
dd if=$1 of=rootfs.gz   bs=1 skip=2482176  count=7243081  status=progress
echo Ungzip rootfs.es...
gzip -d rootfs.gz
echo Uncpio rootfs.es...
mkdir rootfs.dir
pushd rootfs.dir
cpio -id < ../rootfs
popd

echo Extract customer.es...
dd if=$1 of=customer.es bs=1 skip=11169792 count=35692544 status=progress
echo Mount customer.es...
mkdir customer.dir
mount customer.es customer.dir
